Ant Class Reference
#include <Ant.h>
Public Member Functions
 Ant ()
 Ant (int x, int y)
virtual ~Ant ()
int getTime ()
void move ()
 Ant * breed ()
bool isMove (int x, int y)
void action ()
Additional Inherited Members
Constructor & Destructor Documentation
Ant() [1/2]
Ant::Ant ()
Ant() is the constructor for an Ant object with no parameters
Referenced by breed().
Ant() [2/2]
Ant::Ant (int x, int y)
Ant() is the constructor for an Ant object with coordinates as parameters, and is initialized with default values. It icrements the count of total and current ants
References Organism::age, Organism::isPrey, numA, totalA, Organism::x, and Organism::y.
~Ant()
Ant::~Ant () [virtual]
~Ant() is the destructor for an Ant object, it decrements the number of current ants
References numA.
Member Function Documentation
action()
void Ant::action () [virtual]
action() processes a regular turn of an ant, moving the ant and checking if it can breed in the current turn
Implements Organism .
References Organism::age, breed(), Organism::canMove, move(), Organism::x, and Organism::y.
breed()
 Ant * Ant::breed () [virtual]
breed() checks the age of the ant and creates a new ant if the age of the ant is at least 3. Upon creating a new ant, moves it into an adjacent cell and resets the age of the current ant
Returns
pointer to the newly born ant or a null object if breeding conditions are not met
Implements Organism .
References Organism::age, Ant(), move(), totalA, Organism::x, and Organism::y.
Referenced by action().
getTime()
int Ant::getTime () [virtual]
getTime() is a getter function for the turns which the ant has been alive
Returns
age of the Ant object
Implements Organism .
References Organism::age.
isMove()
bool Ant::isMove (int x, int y) [virtual]
isMove() checks the state of the given cell to see whether the object can be moved into by an existing Ant
Returns
a boolean for if the cell can be moved into
Implements Organism .
References Organism::x, and Organism::y.
Referenced by move().
move()
void Ant::move () [virtual]
move() attempts to move an ant into an adjacent cell, choosing one randomly and trying the rest. If none of the cases which were tried work, move() calls itself recursively to try again. It also checks whether it is on the edge of the grid, and terminates if the ant is unable to move
Implements Organism .
References gridLen, isMove(), onEdge(), Organism::x, and Organism::y.
Referenced by action(), and breed().
The documentation for this class was generated from the following files:
 Ant.h
 Ant.cpp