Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
 Doodlebug ()
virtual ~Doodlebug ()
 Doodlebug (int x, int y)
int getTime ()
void move ()
 Doodlebug * breed ()
bool isMove (int x, int y)
bool starve ()
void action ()
void simpleMove ()
Private Attributes
int hunger
Additional Inherited Members
Constructor & Destructor Documentation
Doodlebug() [1/2]
Doodlebug::Doodlebug ()
Doodlebug() is the constructor for a Doodlebug object with no parameters
Referenced by breed().
~Doodlebug()
Doodlebug::~Doodlebug () [virtual]
~Doodlebug() is the destructor for a Doodlebug object, it decrements the number of current doodlebugs
References numD.
Doodlebug() [2/2]
Doodlebug::Doodlebug (int x, int y)
Doodlebug() is the constructor for a Doodlebug object with coordinates as parameters, and is initialized with default values. It increments the count of total and current doodlebugs
References Organism::age, hunger, Organism::isPrey, numD, totalD, Organism::x, and Organism::y.
Member Function Documentation
action()
void Doodlebug::action () [virtual]
action() processes a regular turn of an ant, moving the ant and checking if it can breed in the current turn
Implements Organism .
References Organism::age, breed(), Organism::canMove, hunger, move(), starve(), totalD, Organism::x, and Organism::y.
breed()
 Doodlebug * Doodlebug::breed () [virtual]
breed() checks the age of the doodlebug and creates a new doodlebug if the age of the doodlebug is at least 8. Upon creating a new doodlebug, moves it into an adjacent cell and resets the age of the current doodlebug
Returns
pointer to the newly born doodlebug or a null object if breeding conditions are not met
Implements Organism .
References Organism::age, Doodlebug(), move(), totalD, Organism::x, and Organism::y.
Referenced by action().
getTime()
int Doodlebug::getTime () [virtual]
getTime() is a getter function for the turns which the doodlebug has been alive
Returns
age of the Doodlebug object
Implements Organism .
References Organism::age.
isMove()
bool Doodlebug::isMove (int x, int y) [virtual]
isMove() checks the state of the given cell to see whether the object can be moved into by an existing Doodlebug
Returns
a boolean for if the cell can be moved into
Implements Organism .
Referenced by simpleMove().
move()
void Doodlebug::move () [virtual]
move() checks the adjacent cells for prey, and attacks if it can. If it cannot, calls simpleMove() to move the the Doodlebug
Implements Organism .
References canAttack(), gridLen, hunger, onEdge(), simpleMove(), Organism::x, and Organism::y.
Referenced by action(), breed(), and simpleMove().
simpleMove()
void Doodlebug::simpleMove ()
simpleMove() attempts to move a doodlebug into an adjacent cell, choosing one randomly and trying the rest. If none of the cases which were tried work, move() calls itself recursively to try again. It also checks whether it is on the edge of the grid, and terminates if the ant is unable to move
References gridLen, isMove(), move(), onEdge(), Organism::x, and Organism::y.
Referenced by move().
starve()
bool Doodlebug::starve ()
starve() checks the hunger of the doodlebug and kills off the doodlebug if the hunger conditions are met.
Returns
boolean indicating whether the doodlebug starved or not
References hunger, Organism::x, and Organism::y.
Referenced by action().
Member Data Documentation
hunger
int Doodlebug::hunger [private]
Referenced by action(), Doodlebug(), move(), and starve().
The documentation for this class was generated from the following files:
 Doodlebug.h
 Doodlebug.cpp