main.h File Reference
#include `Organism.h`
Functions
bool onEdge (int x, int y)
bool canAttack (int x, int y)
Function Documentation
canAttack()
bool canAttack (int x, int y)
canAttack() returns a boolean indicating whether the object in the given cell coordinates is able to attack
Returns
boolean indicating whether the given cell contains an organism which is able to attack
References Organism::isPrey.
Referenced by Doodlebug::move().
onEdge()
bool onEdge (int x, int y)
onEdge() checks the cell which whose coordinates are passed and returns a boolean indicating whether it is on the edge of the grid or not
Returns
boolean indicating whether the given cell is on the edge
References gridLen.
Referenced by Ant::move(), Doodlebug::move(), and Doodlebug::simpleMove().