Event Class Reference
Event is an abstract class that contains the time an event occurs at.
#include <event.h>
Public Member Functions
 Event ()
virtual Event * add ()
virtual int getTime ()
virtual int getIdle ()
virtual void action_single_line ()
virtual void action_multiple_lines ()
virtual void add_time (int transaction_time)
virtual ~Event ()
Public Attributes
int line
Detailed Description
Event is an abstract class that contains the time an event occurs at.
Constructor & Destructor Documentation
Event()
Event::Event () [inline]
~Event()
virtual Event::~Event () [inline], [virtual]
Member Function Documentation
action_multiple_lines()
virtual void Event::action_multiple_lines () [inline], [virtual]
Reimplemented in Teller , and Customer .
Referenced by EventQueue::getNextMultipleLines().
action_single_line()
virtual void Event::action_single_line () [inline], [virtual]
Reimplemented in Teller , and Customer .
Referenced by EventQueue::getNext().
add()
virtual Event* Event::add () [inline], [virtual]
Reimplemented in Teller , and Customer .
Referenced by sim_multiple_lines(), and sim_single_line().
add_time()
virtual void Event::add_time (int transaction_time) [inline], [virtual]
Reimplemented in Teller .
Referenced by Customer::action_single_line().
getIdle()
virtual int Event::getIdle () [inline], [virtual]
Reimplemented in Teller .
Referenced by Customer::action_single_line().
getTime()
virtual int Event::getTime () [inline], [virtual]
Reimplemented in Teller , and Customer .
Referenced by Customer::action_single_line(), CompareEvents::operator()(), and Teller::process_transaction().
Member Data Documentation
line
int Event::line
Referenced by sim_multiple_lines().
The documentation for this class was generated from the following file:
 event.h