Customer Class Reference
Customer is a derived Event class that contains information on how long a customer was in the bank for.
#include <customer.h>
Public Member Functions
 Customer ()
 Customer (int t)
 Event * add ()
int getTime ()
void action_single_line ()
void action_multiple_lines ()
virtual ~Customer ()
Public Attributes
int time
Detailed Description
Customer is a derived Event class that contains information on how long a customer was in the bank for.
Constructor & Destructor Documentation
Customer() [1/2]
Customer::Customer () [inline]
Customer() [2/2]
Customer::Customer (int t) [inline]
References action_multiple_lines(), action_single_line(), add(), getTime(), and t.
~Customer()
virtual Customer::~Customer () [inline], [virtual]
Member Function Documentation
action_multiple_lines()
void Customer::action_multiple_lines () [virtual]
action_multiple_lines() runs the action for a customer when there are multiple teller queues. this function effectively figures out which line is shortest and adds a customer to that corresponding line if multiple lines have the same length the customer is added to a random line.
Reimplemented from Event .
References EventQueue::add(), customers_in_line, and tellers.
Referenced by Customer().
action_single_line()
void Customer::action_single_line () [virtual]
action_single_line() performs the action for a customer in a single line simulation according to the guidelines action_single_line() does as specified in the handout instructions, the first customer in line is taken out and his time is incremented with the idle time of waiting in line. Then the global variables for data being tracked are updated accordingly, such as total_idle_time and times_idle. The customer is then readded to the queue with the updated time. Then a random transaction time is generated for the customer and it is added to his time, and again other global variables are updated, total_time and total_transaction_time get updated.
Reimplemented from Event .
References EventQueue::add(), Event::add_time(), avg_service_time, EventQueue::front(), Event::getIdle(), Event::getTime(), max_time_until_service, EventQueue::remove(), time_in_bank, times_idle, total_idle_time, total_time, and total_transaction_time.
Referenced by Customer().
add()
 Event * Customer::add () [virtual]
add() creates a new Customer event with a random arrival time and returns a pointer to it add() generates a random arrival time using the max simulation time from the command line input to create a random time.
Returns
A pointer to the new customer event created
Reimplemented from Event .
References simulation_time.
Referenced by Customer().
getTime()
int Customer::getTime () [virtual]
getTime() returns the arrival time of a customer object
Returns
The arrival time of a customer
Reimplemented from Event .
Referenced by Customer().
Member Data Documentation
time
int Customer::time
The documentation for this class was generated from the following files:
 customer.h
 customer.cpp