Teller Class Reference
Teller is the derived class of Event that carries additional info such as idle_time for each specific teller.
#include <teller.h>
Public Member Functions
 Teller ()
 Teller (int idle_t)
 Event * add ()
int getTime ()
int getIdle ()
void action_single_line ()
void action_multiple_lines ()
void add_time (int transaction_time)
void process_transaction (int line_number)
virtual ~Teller ()
Public Attributes
int idle_time
int time
Detailed Description
Teller is the derived class of Event that carries additional info such as idle_time for each specific teller.
Constructor & Destructor Documentation
Teller() [1/2]
Teller::Teller () [inline]
Teller() [2/2]
Teller::Teller (int idle_t) [inline]
References action_multiple_lines(), action_single_line(), add(), add_time(), getIdle(), getTime(), and process_transaction().
~Teller()
virtual Teller::~Teller () [inline], [virtual]
Member Function Documentation
action_multiple_lines()
void Teller::action_multiple_lines () [virtual]
action_multiple_lines() either helps a customers or goes idle adds a teller event to the event queue with idle time, or processes a transaction for a customer in the tellers line, if not the teller looks to other lines to see if anyone needs help and if no one does goes idle.
Reimplemented from Event .
References EventQueue::add(), customers_in_line, max_idle_time_back_in_queue, min_idle_time_back_in_queue, simulation_time, tellers, time_in_bank, times_idle, and total_idle_time.
Referenced by Teller().
action_single_line()
void Teller::action_single_line () [virtual]
action_single_line() adds this teller event to a teller_queue using the add function of the event queue class
Reimplemented from Event .
References EventQueue::eq.
Referenced by Teller().
add()
 Event * Teller::add () [virtual]
add() creates a new teller object add() creates a new teller object with a random idle time between the min and max, which are 0 to 5 minutes
Returns
a pointer to the new teller object
Reimplemented from Event .
References max_idle_time, and min_idle_time.
Referenced by Teller().
add_time()
void Teller::add_time (int transaction_time) [virtual]
add_time() adds the transaction_time to the time of the teller
Parameters
transaction_time the time to be added to the teller's total time
Reimplemented from Event .
Referenced by Teller().
getIdle()
int Teller::getIdle () [virtual]
getIdle() returns the idle time of a teller object
Returns
the idle time of a teller object
Reimplemented from Event .
Referenced by Teller().
getTime()
int Teller::getTime () [virtual]
getTime() returns the time of a teller object
Returns
the time of a teller object
Reimplemented from Event .
Referenced by Teller().
process_transaction()
void Teller::process_transaction (int line_number)
process_transaction() processes a transaction for a specific line passed by input process_transaction removes the first event from a teller queue, and generates a random service time, adds it to the customers time and updates globals and readds the teller to the event queue. The customer is not readded as he is done in the bank.
References EventQueue::add(), avg_service_time, customers_in_line, EventQueue::front(), Event::getTime(), EventQueue::remove(), total_time, and total_transaction_time.
Referenced by Teller().
Member Data Documentation
idle_time
int Teller::idle_time
time
int Teller::time
The documentation for this class was generated from the following files:
 teller.h
 teller.cpp