EventQueue Class Reference
EventQueue is a priorty_queue of events, is the global overhead for the entire project.
#include <eventqueue.h>
Public Member Functions
 EventQueue ()
void getNext ()
void getNextMultipleLines ()
 Event * front ()
void remove ()
void add (Event *a)
Public Attributes
std::priority_queue< Event *, std::vector< Event * >, CompareEvents > eq
Detailed Description
EventQueue is a priorty_queue of events, is the global overhead for the entire project.
Constructor & Destructor Documentation
EventQueue()
EventQueue::EventQueue () [inline]
Member Function Documentation
add()
void EventQueue::add (Event * event)
add() takes a pointer to an event and adds it to the queue
References eq.
Referenced by Customer::action_multiple_lines(), Teller::action_multiple_lines(), Customer::action_single_line(), Teller::process_transaction(), sim_multiple_lines(), and sim_single_line().
front()
 Event * EventQueue::front ()
front() returns a pointer to the first element in the queue
Returns
a pointer to the first Event in the queue
References eq.
Referenced by Customer::action_single_line(), and Teller::process_transaction().
getNext()
void EventQueue::getNext ()
getNext() removes the first event in the queue and runs the action for it getNext() takes off the first event and runs the corresponding event, either customer or teller, this function is used for a one line simulation
References Event::action_single_line(), and eq.
Referenced by sim_single_line().
getNextMultipleLines()
void EventQueue::getNextMultipleLines ()
getNextMultipleLines() takes the first event off the queue and runs the action for it, for multiple lines does the same as getNext() function, but used for multiple line simulation instead
References Event::action_multiple_lines(), and eq.
Referenced by sim_multiple_lines().
remove()
void EventQueue::remove ()
remove() removes the first element from the queue
References eq.
Referenced by Customer::action_single_line(), and Teller::process_transaction().
Member Data Documentation
eq
std::priority_queue< Event *, std::vector< Event *>, CompareEvents> EventQueue::eq
Referenced by Teller::action_single_line(), add(), front(), getNext(), getNextMultipleLines(), remove(), sim_multiple_lines(), and sim_single_line().
The documentation for this class was generated from the following files:
 eventqueue.h
 eventqueue.cpp