sim.h File Reference
Functions
void sim_single_line ()
void sim_multiple_lines ()
void print ()
Variables
const int min_idle_time
const int max_idle_time
const int min_idle_time_back_in_queue
const int max_idle_time_back_in_queue
Function Documentation
print()
void print ()
print() prints out all the data being tracked over the course of the simulation
References customers, findStDev(), max_time_until_service, sec_in_min, standard_deviation, times_idle, total_idle_time, total_time, and total_transaction_time.
Referenced by main().
sim_multiple_lines()
void sim_multiple_lines ()
sim_multiple_lines is similar to sim_single_line except it generates all the customers and teller events and behaves as if there were multiple teller lines, one for each teller. The respective actions called are the ones for multiple lines
References Event::add(), EventQueue::add(), all_customers, all_tellers, customers, customers_in_line, EventQueue::eq, EventQueue::getNextMultipleLines(), Event::line, and tellers.
Referenced by main().
sim_single_line()
void sim_single_line ()
sim_single_line runs the simulation for a single teller line The simulation is ran by generating all the customers, tellers and the eventqueue and then running everything according to the actions each object have.
References Event::add(), EventQueue::add(), all_customers, all_tellers, customers, EventQueue::eq, event_queue, EventQueue::getNext(), and tellers.
Referenced by main().
Variable Documentation
max_idle_time
const int max_idle_time
Referenced by Teller::add(), and main().
max_idle_time_back_in_queue
const int max_idle_time_back_in_queue
Referenced by Teller::action_multiple_lines().
min_idle_time
const int min_idle_time
Referenced by Teller::add(), and main().
min_idle_time_back_in_queue
const int min_idle_time_back_in_queue
Referenced by Teller::action_multiple_lines().