filefunctions.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include `filefunctions.h`
#include `tree.h`
Functions
int charAmount (FILE *ftr)
void printOrder (BinaryTree *tree, FILE *ftr)
Function Documentation
charAmount()
int charAmount (FILE * ftr)
filefunctions class has all the functions that read and write to files charAmount takes a file and returns the total number of characters in the file charAmount scans through the file and increments for every character it then returns this number
Parameters
ftr the pointer to the input file
Returns
int: the total number of characters in the file
printOrder()
void printOrder (BinaryTree * tree, FILE * ftr)
printOrder takes a tree and an output file and prints out the words and their counts to the output file printOrder works by using inOrder traversal of the tree since it is a binary tree it is sorted when elements are added, therefore by traversing from the far left all the way to the far right notes it prints in order
Parameters
tree pointer to the tree being printed
ftr pointer to the output file printed to
References BinaryTree::left, printOrder(), BinaryTree::right, BinaryTree::string, and BinaryTree::times.
Referenced by main(), and printOrder().