stringfunctions.h File Reference
#include `tree.h`
Functions
int compareString (int i, char *a, char *b, int alen, int blen)
void printString (char *a)
void addString (char *a, int length, BinaryTree *tree)
void stringCleaner (char *b)
void printOrder (BinaryTree *tree, FILE *ftr)
Function Documentation
addString()
void addString (char * a, int length, BinaryTree * tree)
compareString()
int compareString (int i, char * a, char * b, int alen, int blen)
stringfunctions contains functions that work with strings. compareString compares two string and returns the one which is alphabetically later. comapreString works by comparing individual characters of the input strings, and using their integer values to determine alphabetical order. This function works recursively, and if one string is longer than the other, and they contain all the same characters it will return the on which is longer. This functions is used to determine where strings belong in the binary tree.
Parameters
i the index being compared, input 0 for this in almost all cases
a pointer to a string being compared
b pointer to the second string being compared
alen the length of string a
blen the length of string b
Returns
int:returns 1 if the strings are the same, 0 if the first input is smaller, and 2 otherwise
References compareString().
Referenced by addNode(), and compareString().
printOrder()
void printOrder (BinaryTree * tree, FILE * ftr)
printOrder takes a tree and an output file and prints out the words and their counts to the output file printOrder works by using inOrder traversal of the tree since it is a binary tree it is sorted when elements are added, therefore by traversing from the far left all the way to the far right notes it prints in order
Parameters
tree pointer to the tree being printed
ftr pointer to the output file printed to
References BinaryTree::left, printOrder(), BinaryTree::right, BinaryTree::string, and BinaryTree::times.
Referenced by main(), and printOrder().
printString()
void printString (char * a)
printString consumes a string and prints it out printString consumes a pointer to a string and prints it out, not a complex function, but one used a lot, made to clean up repetition
Parameters
a a pointer to a string being printed
stringCleaner()
void stringCleaner (char * s)
stringCleaner consumes a string and cleans it of any punctuation or non alphabetical chars stringCleaner loops through and checks all the characters to make sure they are either char or ' or - and if not removes them it also places a terminating character at the end of the string.
Parameters
s the string to be cleaned
Referenced by main().