tree.h File Reference
Classes
struct BinaryTree
Typedefs
typedef struct BinaryTree BinaryTree
Functions
 BinaryTree * addNode (char *a, BinaryTree *tree)
int totalWords (BinaryTree *tree)
int specificWords (BinaryTree *tree)
Typedef Documentation
BinaryTree
typedef struct BinaryTree BinaryTree
Function Documentation
addNode()
 BinaryTree* addNode (char * a, BinaryTree * tree)
Tree class has all the functions that work with binary treesaddNode takes a string and a binary tree and returns a pointer to the new tree with the added element addNode works by using compareString to find the correct spot for the node within the tree and places it there recursively. If string is already in tree, its times field is incremented
Parameters
a the string to be added to the tree, or if already in increment the number of times
tree the tree to be added to
Returns
BinaryTree* returns a pointer to the new tree with added node
References addNode(), compareString(), BinaryTree::left, BinaryTree::length, BinaryTree::right, BinaryTree::string, and BinaryTree::times.
Referenced by addNode(), and main().
specificWords()
int specificWords (BinaryTree * tree)
specificWords takes a tree and returns the number of unique words within Works identical to total words but instead it only adds one not the amount of times a string appears. Works by recursively going down the tree and adding 1 for every node.
Parameters
tree the tree that has all the words in it to be counted
Returns
int: the amount of unique words in the tree
References BinaryTree::left, BinaryTree::right, and specificWords().
Referenced by main(), and specificWords().
totalWords()
int totalWords (BinaryTree * tree)
totalWords takes a tree and returns the number of words(including repeats) totalWords works similar to printOrder it traverses the tree in order and adds all the words recursively
Parameters
tree the tree that all the strings are stored in
Returns
int: the total number of words in the tree
References BinaryTree::left, BinaryTree::right, BinaryTree::times, and totalWords().
Referenced by main(), and totalWords().